### ISSUE TITLE
Makefile: build settings not respected

### ISSUE THREAD

**Issue by vapier** [jinglewu/etphidiap#1]
the build should be using CFLAGS/CPPFLAGS when compiling and CFLAGS/LDFLAGS when linking

**Comment by jinglewu** [comment]
I have already modify Makefile, please check whether it is correct?

**Comment by vapier** [comment]
the compile line is still incorrect. it should be using cppflags, not ldflags

**Comment by jinglewu** [comment]
vapier, modify LDFLAGS -> CPPFLAGS

**Comment by vapier** [comment]
looks OK now, thanks
